### ISSUE TITLE
Example of how to connect to stream writer

### ISSUE THREAD

**Issue by Keeo** [Amorano/Jovimetrix#1]
Great addon, could you please share a nexample how to use the stream writer?

**Comment by The-Scout** [comment]
Streamwriter currently broken.

**Comment by Amorano** [comment]
https://github.com/Amorano/Jovimetrix/issues/3#issuecomment-1872673962

There is an example there. It wasnt exposed to be used, but since there are a few people who want to try, there ya go!

Just note that removing them doesnt immediately remove the threads running the servers for them, in case you are trying to make them run in automated workflows.

They are fine on Auto-Q though. Have fun!
