### ISSUE TITLE
unhashable type: 'list' error when using GLSL

### ISSUE THREAD

**Issue by tastez** [Amorano/Jovimetrix#17]
File "enum.py", line 790, in __getitem__
TypeError: unhashable type: 'list'

wonder if this is due to an update. All GLSL nodes seem broken

also fyi all image links on repo are broken

**Comment by Amorano** [comment]
Yeah, could be the update. The GLSL node is very finicky. I have no problems when pulling out a new one, could just be the update.

Btw, the images are not broken, they are temp. If they were broken, they wouldnt show 404, they'd be empty.

**Comment by tastez** [comment]
ah well! thanks for the response.

**Comment by Amorano** [comment]
I am making updates to the updates. The glsl (specific) nodes are getting updated to support the batching of all the other nodes.

**Comment by tastez** [comment]
does the glsl stuff even need anything to do with SD to run realtime in the UI?

**Comment by Amorano** [comment]
> does the glsl stuff even need anything to do with SD to run realtime in the UI?

Not sure what you mean. The GLSL is running off modernGL which is in its own context. It could 100% free render, "realtime" all times, as it already is. I a merely telling it which "time slice" to render -- or not, depends on the script.

Comfy isnt really good for "realtime" even with super fast cards.

You can auto-q and the GLSL will free-run as fast as comfy will allow (0.01ms is the lowest I can get which is barely 60fps).

The bug here is that the update didnt include the offshoot GLSL Micro nodes with batching when I did the batching.

**Comment by tastez** [comment]
ah thanks - yeah i was wondering if you were working on a glsl comfy based node editor that could run realtime. All clear!
