### ISSUE TITLE
📺 STREAM READER is causing comfy to try and open the webcam, even if the workflow doesn't contain any nodes

### ISSUE THREAD

**Issue by stephantual** [Amorano/Jovimetrix#25]
To reproduce, simply install jovimetrix, place a stream reader and use it once. 
Afterwards, it tries to open the webcam everytime any worfklow is open, and dumps a bunch of info in the logs such as:
(truncated for simplicity).

This is WITHOUT any stream node in the worfklow, that is, even on a 'clear' page, it does it.

Thank you.

```
[ERROR:0@351.669] global obsensor_uvc_stream_channel.cpp:156 cv::obsensor::getStreamChannelGroup Camera index out of range
 [INFO] [DSH]  python.exe
 [INFO] [DSH]  Creating WndMsg Listener Window
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Performing initializing sequence
 [INFO] [DSH]  Get MessageBus interface succeeded
 [WARN] [DSH]  MessageBus perform initialize in progress
 [WARN] [DSH]  MessageBus perform start in progress
 [INFO] [MBHB] Updating MB Status
 [INFO] [MBHB] Previous marked bus status : Reserved : 0 | Core : 0 | NvContainer Plugin : 0 | DShow Filter : 0 | Camera UI Backend : 0 | Audio UI Backend : 0 |
 [INFO] [MBHB] Bus connected. (5) peers connected : Audio UI Backend, Core, DShow Filter, NvContainer Plugin, Camera UI Backend
 [INFO] [MBHB] Marked joined / connected for module (1) Core
 [INFO] [MBHB] Marked joined / connected for module (2) NvContainer Plugin
 [INFO] [MBHB] Marked joined / connected for module (3) DShow Filter
 [INFO] [MBHB] Marked joined / connected for module (4) Camera UI Backend
 [INFO] [MBHB] Marked joined / connected for module (5) Audio UI Backend
 [INFO] [DSH]  Self joined the MessageBus
 [INFO] [MBHB] Updated marked bus status  : Reserved : 0 | Core : 1 | NvContainer Plugin : 1 | DShow Filter : 1 | Camera UI Backend : 1 | Audio UI Backend : 1 |
 [INFO] [DSH]  Request to get container state
 [INFO] [DSH]  Successfully fetched the GPU details
 [INFO] [DSH]  Found matching GPU for CUDA and D3D
 [INFO] [DSH]  Chosen GPU for D3D: (0) NVIDIA GeForce RTX 4090 : 52450, 0
 [INFO] [DSH]  Request to start core exe
 [INFO] [DSH]  Core reported already running -- Verifying
 [INFO] [DSH]  Verified core exe started
 [INFO] [DSH]  Request to wait for core launch init
 [INFO] [DSH]  Core launch init is done
 [INFO] [DSH]  Request to post cmd for core init
 [INFO] [DSH]  Core initializing now
 [INFO] [DSH]  Initializing streaming output
```

**Comment by Amorano** [comment]
Correct, it autodetected on startup. You can disable that with the [instructions in the readme](https://github.com/Amorano/Jovimetrix?tab=readme-ov-file#system-device-scan)

Set the variable to 0 to turn off the startup autoscan for cameras. This will mean you need to manually enter the camera index yourself (typically 0 or 1).

**Comment by Amorano** [comment]
I am not seeing this behavior, the specific one you have here.

You can turn off the auto-camera detect on startup, but I am not seeing subsequent use cause any weirdness in my logs or attempt to refire.

If you want to disable that with the [instructions in the readme](https://github.com/Amorano/Jovimetrix?tab=readme-ov-file#system-device-scan) you can see if that helps, but it sounds like you have something else going on as all that information dump is completely alien to me in terms of my own internal code or CV2. 

Set the variable to 0 to turn off the startup autoscan for cameras. This will mean you need to manually enter the camera index yourself (typically 0 or 1).

My feeling: Some other library you have is trying to use a different version of CV2 than the global version -- something like headless -- and that causes all sorts of weird issues. 

Check your installation for cv2 to see if you have multiple cv installations.

![image](https://github.com/Amorano/Jovimetrix/assets/225178/101f0da1-62b0-4cc9-9a5b-9e15124fb5d2)

Is all I have, as I clean out the headless and other installations when I update everyone's repositories since they cause all sorts of problems.

HTH

**Comment by stephantual** [comment]
indeed i think it's a cv2 conflict, it's really hard to tell which node is invoking what at this point as I have 103 (yes) node sets installed. I'll turn off autoscan :) thank you!
