### ISSUE TITLE
How to use stream node?

### ISSUE THREAD

**Issue by maciekpoplawski** [Amorano/Jovimetrix#3]
Hi! What a wonderful nodes! 
The webcam input work's like magic. But im having trouble with the stream node. Can you provide a super simple example how it works?

**Comment by maciekpoplawski** [comment]
This is how it's connected
![image](https://github.com/Amorano/Jovimetrix/assets/54249329/2be369f4-b0bc-4bf2-9bd2-81cdff48196a)
But where is the /stream? :)

**Comment by The-Scout** [comment]
Also how do you stream via [SRS](https://github.com/ossrs/srs), or other server?

**Comment by Amorano** [comment]
> Also how do you stream via [SRS](https://github.com/ossrs/srs), or other server?

Not sure how that can be done. I serve the data to a server that I spin up, its not forwarding to URLs; it is making endpoints on a server using the built-in http.server from python. If the SRS can grab from an HTTP server end point, like OBS, you should be good. I see that it can grab FROM OBS, so a weird hack would be to pump it out, back into OBS, then from OBS into SRS.

I havent made it explicit to use because I am unsure if I want to support what I currently have. If you want to see the data, the default port is at 7227, so you would go to 127.0.0.1:7227 + the route in the window. I will push some changes to expose that better for you to try.

http://127.0.0.1:7227/stream for the default.

![image](https://github.com/Amorano/Jovimetrix/assets/225178/53cadf87-abcb-4fec-b79a-019ae6f50225)

As an example of current use. I am using the camera on my system (index 0) to output (using the auto-queue) into the writer (an output node only now) which is streaming the data to http://127.0.0.1:7227/stream

Let me know in what ways it could better serve the needs of the many.
