### ISSUE TITLE
Inputs and Outputs do not have sensible labels

### ISSUE THREAD

**Issue by albamuth** [Amorano/Jovimetrix#36]
Please add text labels to your inputs and outputs, instead of just icons. This is like obfuscated code.

**Comment by Amorano** [comment]
Sorry. Its emoji. You can use the tooltips if you need help. Click a node, use the help button at the top right or hold CTRL+ALT and see the tooltip panel.

The emojis arent changing until the ComfyUI system allows inputs and outputs to be renamed without breaking things.

**Comment by albamuth** [comment]
It's less frustrating to reconnect nodes with intuitive connections after an update than to spend hours deciphering a highly idiosyncratic labeling convention, with poor documentation.

**Comment by Amorano** [comment]
> It's less frustrating to reconnect nodes with intuitive connections after an update than to spend hours deciphering a highly idiosyncratic labeling convention, with poor documentation.

And you think being rude about my free work will help you?

You don't like it, don't use it. Otherwise learn to use the abstract symbols for the things that exist. 

If it was in a foreign language, you would yell at me for English too, right?

Why not be your OWN HERO and do some translation fix for everyone one since it is that much of a problem for you?

Or, again, do you think attempting to smartass your way into my worklist is the best way?
