### ISSUE TITLE
Jovimetrix crashes comfyui

### ISSUE THREAD

**Issue by lunanane** [Amorano/Jovimetrix#52]
Hello,

As reported by multiple users a bug occurs that broke comfyui and it seemed to be caused by Jovimetrix nodes as I just figured.

https://www.reddit.com/r/comfyui/comments/1f0i6jc/comfyui_stopped_working_strangly_chrome/

I also left a bug report here, but essentially cant see much in the logs about why it occurs to my knowledge.

https://github.com/Comfy-Org/ComfyUI_frontend/issues?q=is%3Aissue+is%3Aopen+label%3A%22Potential+Bug%22

Also updateing Jovimetrix didnt help, i had to remove it for now from the node list in order to get ComfyUI running.

**Comment by Amorano** [comment]
Thanks, but! [As I mentioned in the issue thread from HCL](https://github.com/Amorano/Jovimetrix/issues/51#issuecomment-2315754677), this is NOT a Jovimetrix problem it is a problem for the decoder in ClipEncoder and/or you have Metamask turned on in your browser.

Sorry! :(

**Comment by lunanane** [comment]
But is decoder in ClipEncoder somehow related to Jovimetrix repo or how does it influence it in your understasnding? Because it is really only that repo and I tested with about 20 other ComfyUI custom nodes.

**Comment by Amorano** [comment]
> But is decoder in ClipEncoder somehow related to Jovimetrix repo or how does it influence it in your understasading? Because it is really only that repo and I tested with about 20 other ComfyUI custom nodes.

Nope. Nothing to do with me. In the case on that ticket it is some random ClipEncoder...py thing in his custom nodes. In your case, I would imagine it is something else that is trying to encode/decode to something *other than* Unicode. 

Just because mine triggers the problem to show, doesnt mean my repository is the actual cause.

You can see that with all the people who had the same problem and don't actually use my repository and all the people who do use it and do not experience this problem.

If you have any logs/console/exceptions, please make sure to post them so we can trace what specific thing is the actual problem.

I wish I could say it is my problem and find a solution -- it just does not seem to be.
