### ISSUE TITLE
xy random value

### ISSUE THREAD

**Issue by metamountain** [Amorano/Jovimetrix#64]
Could you tell me how to put in random values fo x and y (min max)? I dont know how to do it, because x y is one value....

![image](https://github.com/user-attachments/assets/4d585398-fb37-4de5-9a21-ac0253cdd5c5)

**Comment by metamountain** [comment]
Often work  with batch load , so that would be handy...

**Comment by Amorano** [comment]
you could use a "VALUE" node which will output a VEC2, or, you can build a VEC2 from something else, with random "inputs":

![image](https://github.com/user-attachments/assets/313a46ea-d644-4a5b-a40a-ff0a54fb8cbb)

The vectors run (x, y, z, w) [the columns]
The MIN is the row on top for each
The MAX is the row on bottom for each

HOWEVER

Jovimetrix uses normalized coordinates (-1...1) so there is no way you will be able to use a random from -20 to 512 as an offset. You would need to calculate the normalized version of that first i.e. :

minimum: (-20 / 512) == -0.0390625
maximum: 1.0

so that would look like:

![image](https://github.com/user-attachments/assets/3eee9bbd-16cb-4292-ac97-beefe0ef6ac7)

To give the random ranges of:

X == -0.0390625 -> 1.0 (-20 to 512 if your image is 512 wide)
Y == -0.0390625 -> 1.0 (-20 to 512 if your image is 512 high)

![image](https://github.com/user-attachments/assets/62084d9c-53fa-4e76-9659-b15484206ee7)

Let me know if those are not the results you get.
