### ISSUE TITLE
Flatten - should work with masks and non-alpha (rgb) images

### ISSUE THREAD

**Issue by paxin** [Amorano/Jovimetrix#69]
![Flatten-rgb-issue](https://github.com/user-attachments/assets/894be787-6985-42eb-9a45-a6d6fadccb84)

Here I have simple workflow with two masks isolating each person, the flatten node should be putting them back together in one image. Or it should be at least putting one image on top of the other. However, it seems to be outputting nothing. And the mask output is nothing.

**Comment by Amorano** [comment]
If I understand what you are trying to do, you want to combine both "segments" onto the same canvas? The way you have it now, combining the image with its own mask on top of a black canvas, will indeed, give you black. You could try inverting the mask? perhaps? 

I am not sure it will combine both (i.e. flatten) but I will try to get a working setup to match what you are doing.

**Comment by paxin** [comment]
Thank you for responding! Maybe I'm misunderstanding how this node works, but I was expecting that both people would be isolated since we have a mask batch and an image batch. The flatten should put them back in one image somehow right? I'm not sure why both outputs from the flatten node are black.

**Comment by paxin** [comment]
![Flatten-rgb+invert](https://github.com/user-attachments/assets/4b766353-f242-408c-8714-436084314e97)
Here I've added an invert node and it doesn't seem to change the results. These images have the workflow embedded btw.

**Comment by paxin** [comment]
![Flatten-rgba-issue](https://github.com/user-attachments/assets/b321f9b6-4391-4f1d-bd0f-655346538504)
In this example I've now made the input to the flatten node rgba with a alpha by mask node. This is closer to what I expect, but the areas of overlap are added together, making them brighter. It would make more sense if there was no "transfer" and the overlap was one image or the other. Maybe controllable by input order or widget options?

**Comment by Amorano** [comment]
> Thank you for responding! Maybe I'm misunderstanding how this node works, but I was expecting that both people would be isolated since we have a mask batch and an image batch. The flatten should put them back in one image somehow right? I'm not sure why both outputs from the flatten node are black.

Correct, it should merge the input(s) into a single image. 

![image](https://github.com/user-attachments/assets/0f8f7dd5-eb0c-4c2e-a0e9-b4b09d7040ec)

i have more or less reconstructed the workflow and notice the flatten is not working as it should. I will go ahead and make a patch.

**Comment by Amorano** [comment]
> In this example I've now made the input to the flatten node rgba with a alpha by mask node. This is closer to what I expect, but the areas of overlap are added together, making them brighter. It would make more sense if there was no "transfer" and the overlap was one image or the other. Maybe controllable by input order or widget options?

![image](https://github.com/user-attachments/assets/bdc4669c-3dc5-46b6-9d27-7b2a6cfd23b6)

The latest version (1.2.57) should fix this compositional problem. 

Let me know if that resolves it or you can just close the ticket =D

**Comment by paxin** [comment]
I'm not sure. Here's a more robust workflow that shows exactly what I'm trying to do. Its a setup that attempts to reproduce how adetailer works in A1111, masking n features (in this case people), enhancing them, and then comping them back into the original image. The after the second sampler I have n images in a batch that need to be merged back - flatten should do this right? 
![Flatten-rgb-exd](https://github.com/user-attachments/assets/1c7a0bc3-340e-43f0-9036-f520c905d584)
In your example it appears you are using flatten to merge masks, but there are already many nodes that do that. Flatten is the only one I know of that will merge non-mask images. So how can we put the updated people back together into the orginal background?

**Comment by Amorano** [comment]
> I'm not sure. Here's a more robust workflow that shows exactly what I'm trying to do. Its a setup that attempts to reproduce how adetailer works in A1111, masking n features (in this case people), enhancing them, and then comping them back into the original image. The after the second sampler I have n images in a batch that need to be merged back - flatten should do this right?

That is not what `FLATTEN` does. FLATTEN is a Compositing ADD (slap comp). It is used to merge down images, typically masks, into a single image.

You want to "replace" the original people with the "detailed" version. That is simply a BLEND + MASK operation, though I am somewhat confused, as you should just detail the area you want (the masked area).

> In your example it appears you are using flatten to merge masks, but there are already many nodes that do that. Flatten is the only one I know of that will merge non-mask images. So how can we put the updated people back together into the orginal background?

Correct, because that is the intention of `FLATTEN` i.e. to mostly merge multiple mask images (or color images just depends on what you want), but it is an `ADD` compositing operation.

Given you are attempting to flatten two full color images, your result is 100% accurate as to what `FLATTEN` does.

If you want to detail the people separate and `RE-COMPOSITE` them on top, you need to be using a `BLEND` with a proper `MASK`. You should just use your original "mask" and apply it with your new outputs.

Here is an example of what I mean (partially shown in my last example -- without a flatten since you dont need it):

![image](https://github.com/user-attachments/assets/25fec361-4522-426f-9723-6859ee310bdf)

Thing to note: Since you want the "people" detailed, you need to "invert" the mask when you composite them back into the scene (i.e. white is the 'alpha' mask in my nodes, not 'matte' like ComfyUI uses).

My `BLEND` has a built in "invert" (the second red arrow) to show I am "inverting" the MATTE to keep the background in the A input of the `BLEND` node. The B input is the new "image" which will replace the people with the new "detailed" version.

I do not use those in-painting nodes (for crop and stitch) but you can easily slip yours into the workflow and continue. Here is the workflow from the image with the `MASK`ing done as the example.

[hikers.json](https://github.com/user-attachments/files/18278869/hikers.json)

HTH

**Comment by paxin** [comment]
Thanks for the help! I think I have a better understanding. I'm still using FLATTEN to merge down batched detailed people since I'm working with images much larger than 512. But I've updated and I've added the blend node as well. And the outputs from the FLATTEN node work as expected now. 
Thanks for your work on these nodes, cheers!
